imagePullSecrets:
  - name: ghcr-secret

frontend:
  replicaCount: 3

  image:
    repository: ghcr.io/arnaudcedric/phegonbank-frontend
    tag: "sha-1021e26"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

backend:
  replicaCount: 4

  image:
    repository: ghcr.io/arnaudcedric/backend_bankapp_springboot
    tag: "80e38ed"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  env:
    port: 8080
    jwtExpirationTime: "2592000000"

  config:
    databaseName: bank
    bucketName: arnauds3

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

mysql:
  replicaCount: 1

  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3306
    targetPort: 3306

  storage:
    size: 5Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

ingress:
  enabled: true
  className: nginx
  host: ""