apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory }}
              cpu: {{ .Values.backend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory }}
              cpu: {{ .Values.backend.resources.limits.cpu }}

          ports:
            - containerPort: {{ .Values.backend.env.port }}

          env:
            # ConfigMap
            - name: LOCAL_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: LOCAL_DB_URL

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT

            - name: JWT_EXPIRATION_TIME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: JWT_EXPIRATION_TIME

            - name: AWS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: AWS_BUCKET_NAME

            # MySQL Secret
            - name: LOCAL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: LOCAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            # Backend Secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_ACCESS_KEY

            - name: AWS_SECRETE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_SECRETE_KEY
