apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  JWT_SECRET: cedricarnaud123456789phegon1234567890arstac12343214
  AWS_ACCESS_KEY: AKIA335BJAIJAK4MGP7O
  AWS_SECRETE_KEY: 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
