apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.mysql.replicaCount }}

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}

          resources:
            requests:
              memory: {{ .Values.mysql.resources.requests.memory }}
              cpu: {{ .Values.mysql.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mysql.resources.limits.memory }}
              cpu: {{ .Values.mysql.resources.limits.cpu }}
            

          ports:
            - containerPort: {{ .Values.mysql.service.targetPort }}

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
