apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: bank
  MYSQL_USER: bankuser
  MYSQL_PASSWORD: bankpass
